# Generated by Django 5.2.5 on 2025-08-26 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RetrivalAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='creativity_level',
            field=models.CharField(choices=[('factual', 'Factual'), ('creative', 'Creative'), ('balanced', 'Balanced')], default='balanced', max_length=20),
        ),
    ]
