# Generated by Django 4.2.7 on 2025-08-26 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RetrivalAPI', '0002_alter_project_creativity_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thread_id', models.CharField(max_length=255)),
                ('checkpoint_ns', models.CharField(max_length=255)),
                ('data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
