# Generated by Django 4.2.7 on 2025-08-26 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RetrivalAPI', '0003_checkpoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='scene',
            name='title',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
