# Generated by Django 4.2.7 on 2025-08-28 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RetrivalAPI', '0004_scene_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('story', 'Story'), ('commercial', 'Commercial')], default='story', max_length=20),
        ),
    ]
