# Generated by Django 4.2.7 on 2025-08-29 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RetrivalAPI', '0005_project_project_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Checkpoint',
        ),
    ]
