# Generated by Django 5.2.5 on 2025-08-30 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RetrivalAPI', '0007_workflowcheckpoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowcheckpoint',
            name='version',
            field=models.IntegerField(default=1),
        ),
    ]
