# Generated by Django 5.2.5 on 2025-08-30 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RetrivalAPI', '0008_workflowcheckpoint_version'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='workflowcheckpoint',
            unique_together={('thread_id', 'version')},
        ),
    ]
