# Generated by Django 5.2.5 on 2025-08-30 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RetrivalAPI', '0009_alter_workflowcheckpoint_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflowcheckpoint',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='workflowcheckpoint',
            name='thread_id',
            field=models.TextField(),
        ),
    ]
