# Generated by Django 4.2.7 on 2025-09-19 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RetrivalAPI', '0011_character'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='temp/'),
        ),
        migrations.AlterField(
            model_name='character',
            name='image',
            field=models.TextField(blank=True),
        ),
    ]
