# Generated by Django 4.2.7 on 2025-09-25 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RetrivalAPI', '0012_character_image_file_alter_character_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='trigger_word',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
