# Generated by Django 4.2.7 on 2025-10-19 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RetrivalAPI', '0013_project_trigger_word'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='video',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='scene',
            name='image',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='scene',
            name='image_prompt',
            field=models.TextField(blank=True),
        ),
    ]
