# Generated by Django 4.2.7 on 2025-12-10 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RetrivalAPI', '0014_project_video_scene_image_scene_image_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='scene',
            name='sec_image',
            field=models.TextField(blank=True),
        ),
    ]
