# Generated by Django 4.2.7 on 2025-12-11 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RetrivalAPI', '0015_scene_sec_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scene',
            name='sec_image',
        ),
    ]
